In [1]:

import pandas as pd
import seaborn as sns
from sklearn.linear_model import LogisticRegression
from sklearn.model_selection import train_test_split
from sklearn.metrics import accuracy_score, precision_score

In [3]:
df = pd.read_csv("dataset/iris.csv")
df.head()
df.sample(10)

,Id,SepalLengthCm,SepalWidthCm,PetalLengthCm,PetalWidthCm,Species
120,121,6.9,3.2,5.7,2.3,Iris-virginica
32,33,5.2,4.1,1.5,0.1,Iris-setosa
71,72,6.1,2.8,4.0,1.3,Iris-versicolor
34,35,4.9,3.1,1.5,0.1,Iris-setosa
148,149,6.2,3.4,5.4,2.3,Iris-virginica
122,123,7.7,2.8,6.7,2.0,Iris-virginica
47,48,4.6,3.2,1.4,0.2,Iris-setosa
105,106,7.6,3.0,6.6,2.1,Iris-virginica
59,60,5.2,2.7,3.9,1.4,Iris-versicolor
76,77,6.8,2.8,4.8,1.4,Iris-versicolor

In [6]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 150 entries, 0 to 149
Data columns (total 6 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   Id             150 non-null    int64
 1   SepalLengthCm  150 non-null    float64
 2   SepalWidthCm   150 non-null    float64
 3   PetalLengthCm  150 non-null    float64
 4   PetalWidthCm   150 non-null    float64
 5   Species        150 non-null    str
dtypes: float64(4), int64(1), str(1)
memory usage: 7.2 KB

In [9]:
X = df.drop("Species", axis = 1)
y = df["Species"]

   Id  SepalLengthCm  SepalWidthCm  PetalLengthCm  PetalWidthCm
0   1            5.1           3.5            1.4           0.2
1   2            4.9           3.0            1.4           0.2
2   3            4.7           3.2            1.3           0.2
3   4            4.6           3.1            1.5           0.2
4   5            5.0           3.6            1.4           0.2

In [10]:
X_train , X_test, y_train, y_test = train_test_split(
    X, y, test_size = 0.5, random_state = 42)

X_train.head()

      Id  SepalLengthCm  SepalWidthCm  PetalLengthCm  PetalWidthCm
84    85            5.4           3.0            4.5           1.5
148  149            6.2           3.4            5.4           2.3
53    54            5.5           2.3            4.0           1.3
5      6            5.4           3.9            1.7           0.4
93    94            5.0           2.3            3.3           1.0

In [12]:

from sklearn.preprocessing import StandardScaler
from sklearn.neighbors import KNeighborsClassifier

scaler = StandardScaler()
X_train_scaler = scaler.fit_transform(X_train)
X_test_scaler = scaler.transform(X_test)

X_test.head()

      Id  SepalLengthCm  SepalWidthCm  PetalLengthCm  PetalWidthCm
73    74            6.1           2.8            4.7           1.2
18    19            5.7           3.8            1.7           0.3
118  119            7.7           2.6            6.9           2.3
78    79            6.0           2.9            4.5           1.5
76    77            6.8           2.8            4.8           1.4

In [15]:

knn_class = KNeighborsClassifier(n_neighbors = 5)
knn_class.fit(X_train_scaler, y_train)

KNeighborsClassifier()

In [27]:
from sklearn.metrics import recall_score, f1_score

y_pred = knn_class.predict(X_test_scaler)

print("Accuracy: ",accuracy_score(y_test, y_pred))
print("precision :",precision_score(y_test, y_pred))
print("recall :", recall_score(y_test, y_pred))
print("f1 :", f1_score(y_test, y_pred))

Accuracy:  1.0

ValueError: Target is multiclass but average='binary'. Please choose another average setting, one of [None, 'micro', 'macro', 'weighted'].