In [2]:
# SUPERVISED LEARNING -
# 2) CLASSIFICATION - Logistic Regression 

import pandas as pd
import seaborn as sns
from sklearn.linear_model import LogisticRegression
from sklearn.model_selection import train_test_split
from sklearn.metrics import accuracy_score, precision_score

In [3]:

heart_df = pd.read_csv("dataset/1-heart.csv")

heart_df.head()

,age,sex,cp,trestbps,chol,fbs,restecg,thalach,exang,oldpeak,slope,ca,thal,target
0,63,1,3,145,233,1,0,150,0,2.3,0,0,1,1
1,37,1,2,130,250,0,1,187,0,3.5,0,0,2,1
2,41,0,1,130,204,0,0,172,0,1.4,2,0,2,1
3,56,1,1,120,236,0,1,178,0,0.8,2,0,2,1
4,57,0,0,120,354,0,1,163,1,0.6,2,0,2,1

In [4]:
heart_df.columns
heart_df.info()
heart_df["target"].nunique()

<class 'pandas.DataFrame'>
RangeIndex: 303 entries, 0 to 302
Data columns (total 14 columns):
 #   Column    Non-Null Count  Dtype
---  ------    --------------  -----
 0   age       303 non-null    int64
 1   sex       303 non-null    int64
 2   cp        303 non-null    int64
 3   trestbps  303 non-null    int64
 4   chol      303 non-null    int64
 5   fbs       303 non-null    int64
 6   restecg   303 non-null    int64
 7   thalach   303 non-null    int64
 8   exang     303 non-null    int64
 9   oldpeak   303 non-null    float64
 10  slope     303 non-null    int64
 11  ca        303 non-null    int64
 12  thal      303 non-null    int64
 13  target    303 non-null    int64
dtypes: float64(1), int64(13)
memory usage: 33.3 KB

2

In [5]:

X = heart_df.drop("target", axis = 1)
y = heart_df["target"]

In [6]:
y.head()

0    1
1    1
2    1
3    1
4    1
Name: target, dtype: int64

In [7]:
# Train Test --

X_train, X_test, y_train, y_test = train_test_split (
    X, y, test_size = 0.2,  random_state =  42
)


model = LogisticRegression(max_iter = 10000)
model.fit(X_train, y_train)

LogisticRegression(max_iter=10000)

In [8]:
y_train[y_train == 1]   #133
y_train[y_train == 0]   #109

202    0
196    0
176    0
177    0
258    0
      ..
257    0
214    0
302    0
188    0
270    0
Name: target, Length: 109, dtype: int64

In [9]:

y_pred = model.predict(X_test)
print("accuracy: ", accuracy_score(y_test, y_pred)*100, "%")
print("precision: ", precision_score(y_test, y_pred)*100, "%")

accuracy:  88.52459016393442 %
precision:  87.87878787878788 %

In [22]:

# Evaluation Metrics--
from sklearn.metrics import confusion_matrix, classification_report, accuracy_score, precision_score, recall_score, f1_score

cm = confusion_matrix(y_test, y_pred)
print(cm)

print(classification_report(y_test, y_pred))

print("accuracy :", accuracy_score(y_test, y_pred))
print("precision :",precision_score(y_test, y_pred))
print("recall :", recall_score(y_test, y_pred))
print("f1 :", f1_score(y_test, y_pred))

[[25  4]
 [ 5 27]]
              precision    recall  f1-score   support

           0       0.83      0.86      0.85        29
           1       0.87      0.84      0.86        32

    accuracy                           0.85        61
   macro avg       0.85      0.85      0.85        61
weighted avg       0.85      0.85      0.85        61

accuracy : 0.8524590163934426
precision : 0.8709677419354839
recall : 0.84375
f1 : 0.8571428571428571

In [12]:

# SCALING -- 
from sklearn.preprocessing import StandardScaler

scalar = StandardScaler()
X_train = scalar.fit_transform(X_train)
X_test  = scalar.transform(X_test)

In [13]:

model = LogisticRegression(max_iter = 10000)
model.fit(X_train, y_train)

y_pred = model.predict(X_test)
print("accuracy: ", accuracy_score(y_test, y_pred)*100, "%")
print("precision: ", precision_score(y_test, y_pred)*100, "%")

accuracy:  85.24590163934425 %
precision:  87.09677419354838 %

In [1]:
# ASSIGNMENT -2

import pandas as pd
import seaborn as sns
from sklearn.linear_model import LogisticRegression
from sklearn.model_selection import train_test_split
from sklearn.metrics import accuracy_score, precision_score

In [3]:

df= pd.read_csv("dataset/employee_turnover.csv")
df.head()

,Job_Satisfaction,Performance_Rating,Years_At_Company,Work_Life_Balance,Distance_From_Home,Monthly_Income,Education_Level,Age,Num_Companies_Worked,Employee_Role,Annual_Bonus,Training_Hours,Department,Annual_Bonus_Squared,Annual_Bonus_Training_Hours_Interaction,Employee_Turnover
0,0.562326,0.141129,0.123989,0.347583,0.330353,0.328853,0.600933,0.315990,0.768736,0.090671,0.324786,0.669193,0.602932,0.105486,0.217344,0
1,0.017041,0.559047,0.511203,0.793908,0.423550,0.553450,0.742009,0.897146,0.380035,0.601633,0.694611,0.043271,0.800761,0.482484,0.030056,0
2,0.774699,0.604371,0.798174,0.260500,0.804034,0.131800,0.775178,0.830947,0.218726,0.972936,0.153476,0.701336,0.705275,0.023555,0.107638,1
3,0.628174,0.385249,0.230104,0.516809,0.272248,0.589249,0.482409,0.090507,0.402746,0.132842,0.305973,0.549688,0.600531,0.093620,0.168190,0
4,0.799183,0.199967,0.839029,0.247927,0.341934,0.076818,0.055356,0.680860,0.923341,0.493017,0.844094,0.793751,0.664679,0.712494,0.670000,0

In [6]:
df.info()
df.describe()

<class 'pandas.DataFrame'>
RangeIndex: 1350 entries, 0 to 1349
Data columns (total 16 columns):
 #   Column                                   Non-Null Count  Dtype
---  ------                                   --------------  -----
 0   Job_Satisfaction                         1350 non-null   float64
 1   Performance_Rating                       1350 non-null   float64
 2   Years_At_Company                         1350 non-null   float64
 3   Work_Life_Balance                        1350 non-null   float64
 4   Distance_From_Home                       1350 non-null   float64
 5   Monthly_Income                           1350 non-null   float64
 6   Education_Level                          1350 non-null   float64
 7   Age                                      1350 non-null   float64
 8   Num_Companies_Worked                     1350 non-null   float64
 9   Employee_Role                            1350 non-null   float64
 10  Annual_Bonus                             1350 non-null   float64
 11  Training_Hours                           1350 non-null   float64
 12  Department                               1350 non-null   float64
 13  Annual_Bonus_Squared                     1350 non-null   float64
 14  Annual_Bonus_Training_Hours_Interaction  1350 non-null   float64
 15  Employee_Turnover                        1350 non-null   int64
dtypes: float64(15), int64(1)
memory usage: 168.9 KB

,Job_Satisfaction,Performance_Rating,Years_At_Company,Work_Life_Balance,Distance_From_Home,Monthly_Income,Education_Level,Age,Num_Companies_Worked,Employee_Role,Annual_Bonus,Training_Hours,Department,Annual_Bonus_Squared,Annual_Bonus_Training_Hours_Interaction,Employee_Turnover
count,1350.000000,1350.000000,1350.000000,1350.000000,1350.000000,1350.000000,1350.000000,1350.000000,1350.000000,1350.000000,1350.000000,1350.000000,1350.000000,1.350000e+03,1350.000000,1350.000000
mean,0.506386,0.487061,0.484761,0.499442,0.494884,0.509909,0.504329,0.500164,0.516149,0.506091,0.493360,0.486843,0.485767,3.291479e-01,0.240653,0.497778
std,0.291505,0.283808,0.282758,0.293013,0.289248,0.290110,0.295693,0.294835,0.295072,0.284901,0.292929,0.288342,0.285077,2.986314e-01,0.222281,0.500180
min,0.001738,0.000546,0.001545,0.000166,0.001319,0.005015,0.000424,0.000231,0.000150,0.000903,0.000491,0.001293,0.001595,2.410000e-07,0.000247,0.000000
25%,0.263051,0.238538,0.249651,0.246399,0.244162,0.263235,0.249894,0.239224,0.247978,0.269517,0.247274,0.233357,0.244944,6.114448e-02,0.058694,0.000000
50%,0.525340,0.468457,0.485414,0.495572,0.501617,0.532388,0.509448,0.499964,0.531408,0.504640,0.498490,0.475214,0.468982,2.484923e-01,0.165438,0.000000
75%,0.750987,0.724088,0.721622,0.753108,0.743938,0.761090,0.755113,0.767168,0.775888,0.761640,0.740231,0.747609,0.725870,5.479425e-01,0.367042,1.000000
max,0.998692,0.999957,0.999722,0.999931,0.997813,0.999143,0.999794,0.998365,0.999962,0.999964,0.998211,0.998330,0.999386,9.964245e-01,0.930338,1.000000

In [14]:

corr = df.corr(numeric_only=True)
print(corr["Employee_Turnover"].sort_values(ascending=False))

Employee_Turnover                          1.000000
Job_Satisfaction                           0.357116
Distance_From_Home                         0.350905
Performance_Rating                         0.340058
Work_Life_Balance                          0.298103
Years_At_Company                           0.296231
Employee_Role                              0.064028
Annual_Bonus_Squared                       0.029532
Age                                        0.024104
Annual_Bonus                               0.018733
Annual_Bonus_Training_Hours_Interaction    0.014852
Training_Hours                             0.008068
Num_Companies_Worked                      -0.004040
Monthly_Income                            -0.033279
Education_Level                           -0.059755
Department                                -0.071534
Name: Employee_Turnover, dtype: float64

In [15]:

X = df.drop(columns = "Employee_Turnover")

y = df["Employee_Turnover"]

df.sample(5)

,Job_Satisfaction,Performance_Rating,Years_At_Company,Work_Life_Balance,Distance_From_Home,Monthly_Income,Education_Level,Age,Num_Companies_Worked,Employee_Role,Annual_Bonus,Training_Hours,Department,Annual_Bonus_Squared,Annual_Bonus_Training_Hours_Interaction,Employee_Turnover
507,0.087837,0.592935,0.398259,0.550329,0.124065,0.786178,0.511956,0.830931,0.206812,0.938084,0.578185,0.075686,0.313718,0.334298,0.043760,0
532,0.163796,0.887499,0.425759,0.438894,0.678472,0.888394,0.744045,0.441348,0.462378,0.278356,0.058392,0.939685,0.099623,0.003410,0.054870,1
506,0.953170,0.513810,0.908092,0.885926,0.885267,0.375802,0.185878,0.351191,0.134277,0.834392,0.568590,0.248582,0.819983,0.323295,0.141342,1
1032,0.231758,0.004239,0.499174,0.356437,0.427119,0.573342,0.076050,0.262791,0.230016,0.886328,0.741239,0.185894,0.838349,0.549436,0.137792,0
1325,0.373388,0.206151,0.800320,0.353164,0.257900,0.762305,0.428617,0.767410,0.739405,0.017606,0.726661,0.206502,0.648627,0.528037,0.150057,0

In [26]:

X["Income_Per_Year"] = ( X["Monthly_Income"] / (X["Years_At_Company"] + 1) )

X["Joining_Age"] = (X["Age"] - X["Years_At_Company"])

X["Happiness_Index"] = (X["Job_Satisfaction"] + X["Work_Life_Balance"])

X["Worke_Load"] = (X["Performance_Rating"] - X["Annual_Bonus"])

X["Performance_Bonus_Ratio"] = (X["Performance_Rating"] /(X["Annual_Bonus"] + 1))

In [42]:
X["Employee_Turnover_Prob"] = 0

X.loc[
    (
        (X["Distance_From_Home"] > X["Distance_From_Home"].mean()) &
        (X["Work_Life_Balance"] < X["Work_Life_Balance"].mean())
    ),
    "Employee_Turnover_Prob"
] = 1

X.loc[
    (
        (X["Monthly_Income"] < X["Monthly_Income"].mean()) &
        (X["Education_Level"] > X["Education_Level"].mean())
    ),
    "Employee_Turnover_Prob"
] = 1


X.drop(columns = "Employee_Turnover_Prob")

,Job_Satisfaction,Performance_Rating,Years_At_Company,Work_Life_Balance,Distance_From_Home,Monthly_Income,Education_Level,Age,Num_Companies_Worked,Employee_Role,...,Department,Annual_Bonus_Squared,Annual_Bonus_Training_Hours_Interaction,Income_Per_Year,Happiness_Index,Worke_Load,Joining_Age,Performance_Bonus_Ratio,Far_And_Unhappy,Underpaid_Graduate
0,0.562326,0.141129,0.123989,0.347583,0.330353,0.328853,0.600933,0.315990,0.768736,0.090671,...,0.602932,0.105486,0.217344,0.292577,0.909910,-0.183657,0.192001,0.106529,0,1
1,0.017041,0.559047,0.511203,0.793908,0.423550,0.553450,0.742009,0.897146,0.380035,0.601633,...,0.800761,0.482484,0.030056,0.366232,0.810949,-0.135564,0.385943,0.329897,0,0
2,0.774699,0.604371,0.798174,0.260500,0.804034,0.131800,0.775178,0.830947,0.218726,0.972936,...,0.705275,0.023555,0.107638,0.073296,1.035200,0.450895,0.032773,0.523956,1,1
3,0.628174,0.385249,0.230104,0.516809,0.272248,0.589249,0.482409,0.090507,0.402746,0.132842,...,0.600531,0.093620,0.168190,0.479024,1.144984,0.079276,-0.139597,0.294990,0,0
4,0.799183,0.199967,0.839029,0.247927,0.341934,0.076818,0.055356,0.680860,0.923341,0.493017,...,0.664679,0.712494,0.670000,0.041771,1.047110,-0.644127,-0.158169,0.108436,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1345,0.914733,0.965914,0.147215,0.686677,0.251346,0.572003,0.089679,0.127247,0.125553,0.346950,...,0.905320,0.203205,0.340194,0.498601,1.601410,0.515131,-0.019969,0.665788,0,0
1346,0.396906,0.182952,0.877941,0.824077,0.774960,0.057290,0.556719,0.235014,0.119685,0.781613,...,0.526096,0.044767,0.105962,0.030507,1.220983,-0.028629,-0.642927,0.151003,0,1
1347,0.099171,0.363498,0.849120,0.462270,0.763922,0.585370,0.975760,0.557090,0.782690,0.384706,...,0.253656,0.201686,0.121381,0.316567,0.561441,-0.085597,-0.292030,0.250845,1,0
1348,0.048193,0.453892,0.640611,0.335230,0.952724,0.638797,0.993664,0.801292,0.510281,0.164325,...,0.405705,0.422414,0.098286,0.389365,0.383423,-0.196042,0.160681,0.275097,1,0
1349,0.496702,0.523527,0.779612,0.320897,0.048957,0.637470,0.908619,0.587263,0.236790,0.265646,...,0.828226,0.128753,0.312521,0.358207,0.817599,0.164706,-0.192350,0.385280,0,0

In [43]:

X["Far_And_Unhappy"] = (
    (X["Distance_From_Home"] > X["Distance_From_Home"].mean()) &
    (X["Work_Life_Balance"] < X["Work_Life_Balance"].mean())
).astype(int)

X["Underpaid_Graduate"] = (
    (X["Monthly_Income"] < X["Monthly_Income"].mean()) &
    (X["Education_Level"] > X["Education_Level"].mean())
).astype(int)

In [44]:
X.sample(5)

,Job_Satisfaction,Performance_Rating,Years_At_Company,Work_Life_Balance,Distance_From_Home,Monthly_Income,Education_Level,Age,Num_Companies_Worked,Employee_Role,...,Annual_Bonus_Squared,Annual_Bonus_Training_Hours_Interaction,Income_Per_Year,Happiness_Index,Worke_Load,Joining_Age,Performance_Bonus_Ratio,Employee_Turnover_Prob,Far_And_Unhappy,Underpaid_Graduate
412,0.052030,0.704574,0.540074,0.676140,0.278231,0.406914,0.192650,0.419683,0.653491,0.944689,...,0.440175,0.348421,0.264217,0.728170,0.041117,-0.120391,0.423560,0,0,0
413,0.324973,0.555297,0.701827,0.448286,0.001319,0.737968,0.201493,0.651192,0.890734,0.409118,...,0.000953,0.028774,0.433633,0.773259,0.524433,-0.050635,0.538672,0,0,0
1339,0.582521,0.917168,0.654263,0.310130,0.175503,0.604308,0.736174,0.824162,0.285288,0.902000,...,0.334051,0.417927,0.365303,0.892651,0.339196,0.169899,0.581232,0,0,0
463,0.118491,0.697574,0.993262,0.391915,0.763739,0.654240,0.420962,0.048934,0.409429,0.029266,...,0.906764,0.389836,0.328226,0.510405,-0.254668,-0.944328,0.357319,1,1,0
1347,0.099171,0.363498,0.849120,0.462270,0.763922,0.585370,0.975760,0.557090,0.782690,0.384706,...,0.201686,0.121381,0.316567,0.561441,-0.085597,-0.292030,0.250845,1,1,0

In [45]:

X_train, X_test, y_train, y_test = train_test_split (
    X, y, test_size = 0.2, random_state = 42)

model = LogisticRegression(max_iter = 10000)
model.fit(X_train, y_train)

LogisticRegression(max_iter=10000)

In [46]:
y_pred = model.predict(X_test)

y_pred

array([0, 0, 1, 0, 0, 0, 1, 1, 0, 1, 1, 1, 0, 0, 0, 0, 1, 0, 1, 0, 0, 0,
       1, 1, 1, 1, 0, 0, 0, 1, 0, 1, 0, 1, 1, 0, 0, 0, 1, 1, 1, 0, 1, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 1, 1, 0, 0, 0, 1, 0, 1, 1,
       0, 0, 0, 1, 1, 0, 0, 0, 0, 1, 0, 0, 1, 1, 0, 1, 1, 0, 0, 1, 0, 0,
       1, 1, 1, 1, 0, 0, 1, 0, 0, 0, 0, 0, 0, 1, 1, 0, 1, 0, 0, 0, 1, 1,
       0, 0, 1, 0, 1, 1, 1, 1, 1, 0, 1, 1, 0, 0, 1, 0, 1, 1, 1, 0, 0, 0,
       1, 0, 1, 0, 1, 1, 1, 0, 1, 1, 0, 1, 0, 1, 1, 0, 0, 0, 1, 0, 0, 1,
       1, 1, 0, 1, 1, 0, 1, 1, 1, 1, 1, 1, 1, 1, 0, 0, 0, 1, 0, 0, 0, 0,
       1, 0, 1, 0, 0, 1, 1, 0, 0, 1, 1, 0, 1, 1, 0, 0, 0, 1, 0, 0, 1, 0,
       0, 1, 0, 1, 0, 1, 0, 0, 0, 0, 0, 1, 1, 1, 0, 1, 1, 0, 0, 1, 1, 0,
       0, 0, 0, 1, 1, 1, 1, 0, 1, 1, 0, 0, 0, 0, 0, 1, 0, 0, 0, 1, 1, 0,
       0, 1, 1, 0, 0, 0, 0, 1, 0, 0, 1, 0, 0, 0, 0, 1, 1, 0, 0, 0, 1, 0,
       0, 1, 0, 0, 1, 0])

In [47]:

print("accuracy: ", accuracy_score(y_test, y_pred)*100, "%")
print("precision: ", precision_score(y_test, y_pred)*100, "%")

accuracy:  87.4074074074074 %
precision:  88.23529411764706 %