In [1]:
import pandas as pd

In [2]:
info = {
    "NAme" : ["Rahul", "Harshita", "Shradha"],
    "cgpa" : [8.7, 6.6, 9.7]
}

df = pd.DataFrame(info)
print(df)

       NAme  cgpa
0     Rahul   8.7
1  Harshita   6.6
2   Shradha   9.7

In [3]:
s = pd.Series([1,2,3,4,5])
print(s)
print(type(s))

# index
print(s[0])
print(s[4])

0    1
1    2
2    3
3    4
4    5
dtype: int64
<class 'pandas.Series'>
1
5

In [4]:
# labeled 
s = pd.Series([15,62,33], index=["Adam", "Daada", "broo"])

print(s)
print(s["Adam"])
print(s["broo"])
print(s.index)

Adam     15
Daada    62
broo     33
dtype: int64
15
33
Index(['Adam', 'Daada', 'broo'], dtype='str')

In [5]:
# properties

# homogeneous - datatype same for all
# vactorised -

s1 = pd.Series([1,2,3,4,5])
s2 = pd.Series([10,20,30,40,50])

print(s1+s2)


# handles missing value with NaN-

# mutable values, immutable size-

s1[0] = 100

changed_s1 = s1.drop(0)

print(s1)
print(changed_s1)

0    11
1    22
2    33
3    44
4    55
dtype: int64
0    100
1      2
2      3
3      4
4      5
dtype: int64
1    2
2    3
3    4
4    5
dtype: int64

In [6]:
# 2d labeled array
# dict  of list -

info = {
    "NAme" : ["Adam", "madam", "Daada", "broo"], 
    "Age" : [34,66,65,86], 
    "Gpa" : [9.6 ,8.5, 8, 9.5]
}

df = pd.DataFrame(info)
print(df, type(df))


print(df.index)
print(df.columns)

    NAme  Age  Gpa
0   Adam   34  9.6
1  madam   66  8.5
2  Daada   65  8.0
3   broo   86  9.5 <class 'pandas.DataFrame'>
RangeIndex(start=0, stop=4, step=1)
Index(['NAme', 'Age', 'Gpa'], dtype='str')

In [7]:
# list of list-
df = pd.DataFrame([["Adam", 23], ["vfd", 78], ["dfv", 65]])

print(df, type(df))

      0   1
0  Adam  23
1   vfd  78
2   dfv  65 <class 'pandas.DataFrame'>

In [8]:
# np arrays -

import numpy as np

np_arr = np.array([[1,2,3], [2,5,7], [3,6,8]])

df = pd.DataFrame(np_arr, columns = ["A", "B", "C"])
print(df)

   A  B  C
0  1  2  3
1  2  5  7
2  3  6  8

In [9]:
# import .csv data using pandas -- df

df = pd.read_csv("employee_data.csv")
print(df, type(df))

# json data

# df = pd.read_json("employee_data.json")

# read_excel, read_sql

   ID     Name  Age Department  Salary
0   1    Alice   25         HR   55000
1   2      Bob   32         IT   72000
2   3  Charlie   28    Finance   48000
3   4    David   45  Marketing   91000
4   5      Eva   38         IT   65000
5   6    Frank   29    Finance   50000
6   7    Grace   41         HR   82000
7   8   Hannah   26  Marketing   47000
8   9      Ian   35         IT   75000
9  10    Julia   30    Finance   60000 <class 'pandas.DataFrame'>

In [10]:
# Methods df--

df.head()   #start 5 row
df.head(3)

df.tail()   #end se 5 row
df.tail(2)

df.sample(5)   #any five

df.info()

df.shape   #tuple

df.describe()

df.nunique()

<class 'pandas.DataFrame'>
RangeIndex: 10 entries, 0 to 9
Data columns (total 5 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   ID          10 non-null     int64
 1   Name        10 non-null     str
 2   Age         10 non-null     int64
 3   Department  10 non-null     str
 4   Salary      10 non-null     int64
dtypes: int64(3), str(2)
memory usage: 532.0 bytes

ID            10
Name          10
Age           10
Department     4
Salary        10
dtype: int64

In [11]:
# AQI DATA SETS-

df = pd.read_csv("globalAirQuality.csv")

df.describe()

,latitude,longitude,pm25,pm10,no2,so2,o3,co,aqi,temperature,humidity,wind_speed
count,18000.000000,18000.000000,18000.000000,18000.000000,18000.000000,18000.000000,18000.000000,18000.000000,18000.000000,18000.000000,18000.000000,18000.000000
mean,23.065980,37.655560,40.369131,70.152228,32.055176,6.035508,48.065100,0.800595,104.645556,21.510251,57.714351,5.283910
std,26.156536,78.600701,17.647450,24.999440,13.820680,2.454790,14.950849,0.250254,25.616070,9.509444,18.844908,2.741712
min,-37.814000,-123.121000,0.025000,0.061000,0.013000,0.003000,0.114000,0.000000,16.000000,5.000000,25.002000,0.500000
25%,12.972000,2.352000,27.904500,53.125500,22.362500,4.360750,38.028500,0.633000,87.000000,13.357750,41.320000,2.937000
50%,29.232000,42.146000,40.286500,69.961000,32.019500,6.026000,48.142000,0.800500,103.000000,21.455500,57.847000,5.297000
75%,41.008000,103.820000,52.436250,87.256500,41.364250,7.715250,58.258500,0.969000,121.000000,29.688250,74.234750,7.662000
max,60.170000,174.763000,115.683000,161.810000,90.019000,16.559000,103.016000,1.832000,231.000000,37.998000,89.997000,9.999000

In [12]:
# Selecting data

# col
df["country"]   #col
df[["city", "aqi"]]

# row
df.loc[0]   #1st row
df.loc[0:4]  #5 is included

df.iloc[2]
df.iloc[0:5]    #5 not included

# row- col
df.loc[0:3, ["city"]]
df.loc[0:2, ["city", "latitude", "longitude", "pm25", "pm10"]]

df.columns
df.iloc[0:4, 2]
df.iloc[0:3, 2:7]

# cell value
df.at[0, "city"]
df.iat[0, 2]


cities = df["city"]   #view not copy
# cities[0] = "Mumbai"   #change in original


cities = df["city"].copy()   #copy
cities[0] = "Mumbai"   #change in copy

In [13]:
# filtering of data-

df[ df["aqi"] > 100]

df[ (df["aqi"] > 100) & (df["temperature"] >30)]
df[ (df["aqi"] > 100) & (df["temperature"] <30)]

aqi_data = df[ (df["aqi"] > 100) & (df["temperature"] >30) ] [ ["city", "aqi"]]

aqi_data.iloc[0]
aqi_data.loc[6]

# query - copy 

aqi_val = 100
df.query("aqi > 100 & temperature > 30") [[ "city", "aqi"]]

# var
aqi_data = df.query("aqi > @aqi_val & temperature > 30").copy()
aqi_data

,timestamp,country,city,latitude,longitude,pm25,pm10,no2,so2,o3,co,aqi,temperature,humidity,wind_speed
6,2025-11-05 00:25:17.554219,US,New York,40.713,-74.006,77.690,65.198,20.302,7.641,62.687,0.734,155,36.729,47.651,4.542
7,2025-11-05 01:25:17.554219,US,New York,40.713,-74.006,57.816,111.709,34.533,6.945,41.304,0.771,115,37.891,53.314,7.605
14,2025-11-05 08:25:17.554219,US,New York,40.713,-74.006,38.815,121.394,25.969,4.112,44.730,1.124,121,34.481,81.790,3.576
17,2025-11-05 11:25:17.554219,US,New York,40.713,-74.006,63.552,57.838,13.754,4.427,42.251,0.997,127,36.193,62.906,7.097
25,2025-11-05 19:25:17.554219,US,New York,40.713,-74.006,56.954,75.045,29.837,9.541,54.198,1.170,113,31.289,43.279,5.264
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
17947,2025-11-17 13:25:17.554219,CH,Zurich,47.377,8.542,53.938,75.183,16.255,7.263,67.244,0.457,107,32.584,81.544,7.101
17950,2025-11-17 16:25:17.554219,CH,Zurich,47.377,8.542,70.255,60.620,32.081,2.065,47.803,0.852,140,36.885,34.173,1.748
17975,2025-11-18 17:25:17.554219,CH,Zurich,47.377,8.542,33.406,98.160,44.654,0.807,45.160,0.737,111,30.761,76.073,3.570
17976,2025-11-18 18:25:17.554219,CH,Zurich,47.377,8.542,73.493,89.558,9.313,4.768,51.505,0.745,146,30.909,81.573,1.024
17991,2025-11-19 09:25:17.554219,CH,Zurich,47.377,8.542,52.120,71.160,35.405,7.752,39.811,0.878,104,32.556,31.372,2.787

In [14]:
# cleaning data --

df = pd.read_csv("raw_data.csv")
df

# missing val-

df.isnull()    #returns true where data is missing
df.isna()

df.isnull().sum()

df.dropna()  #drop null cell row 
df.dropna(axis = 1)

df.fillna(0)

cleaned_df =  df.copy()
age_mean = cleaned_df["age"].mean()

cleaned_df["age"] = cleaned_df["age"].fillna(age_mean)

df.ffill()
df.bfill()

    id          name   age country   gender   income
0    1      John Doe  29.0     USA     Male  55000.0
1    1      John Doe  29.0     USA     Male  55000.0
2    2    Jane Smith  34.0  Canada   Female  62000.0
3    3          Alex  34.0     USA  Unknown  47000.0
4    4  Maria Garcia  34.0   Spain   Female  51000.0
5    5        Li Wei  27.0   China     Male  51000.0
6    6    Ahmed Khan  45.0   India   Female  73000.0
7    7    Ahmed Khan  38.0     USA     Male  68000.0
8    8    Rachel Lee  29.0     USA   Female  62000.0
9    9   Carlos Ruiz  31.0  Mexico     Male  45000.0
10  10   Emily Davis  31.0     USA      NaN  58000.0

In [15]:
# Handles duplicate -

df.duplicated()

df[["country", "gender"]].duplicated()

df2 = df.copy()
df.drop_duplicates(inplace = True)



# string -
df["gender"].str.upper()
df["gender"].str.capitalize()
df["gender"].str.split(" ")
df["gender"].str.contains("india", case = False)

0     False
2     False
3     False
4     False
5     False
6     False
7     False
8     False
9     False
10    False
Name: gender, dtype: bool

In [16]:
# diff data type --

df.dtypes

df2 = df.copy()
df2 = df2.fillna(0)
df2["age"] = df2["age"].astype("int64").copy()

df2.dtypes

id           int64
name        object
age          int64
country     object
gender      object
income     float64
dtype: object

In [17]:
aqi_data = pd.read_csv("globalAirQuality.csv")
aqi_data


date_str = pd.Series( [ pd.to_datetime(["2026-11-4"])])
type(date_str.dtypes)

aqi_data["timestamp"].dtypes

In [1]:
# feature engineering

NameError: name 'df' is not defined